      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps (detect package manager)
        run: |
          if [ -f pnpm-lock.yaml ]; then
            corepack enable
            pnpm install --frozen-lockfile
          elif [ -f yarn.lock ]; then
            corepack enable
            yarn install --frozen-lockfile
          else
            npm install
          fi

      - name: Build
        run: |
          if [ -f pnpm-lock.yaml ]; then
            pnpm build
          elif [ -f yarn.lock ]; then
            yarn build
          else
            npm run build
          fi

      - run: touch dist/.nojekyll
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist
